[project]
name = "visao-computacional"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "facenet-pytorch>=2.6.0",
    "ipykernel>=7.2.0",
    "matplotlib>=3.10.8",
    "opencv-python>=4.11.0.86",
    "pillow>=10.2.0",
    "scikit-learn>=1.8.0",
    "seaborn>=0.13.2",
    "streamlit>=1.54.0",
    "tensorflow>=2.18.1",
    "torch>=2.2.2",
    "torchvision>=0.17.2",
    "ultralytics>=8.4.12",
]
